-- Role: ADMIN → LEAD_SUP, SUPPORT → SUP, CITY_ADMIN → ADM
ALTER TYPE "Role" RENAME VALUE 'ADMIN' TO 'LEAD_SUP';
ALTER TYPE "Role" RENAME VALUE 'SUPPORT' TO 'SUP';
ALTER TYPE "Role" RENAME VALUE 'CITY_ADMIN' TO 'ADM';

-- CityRole: расширение + CITY_ADMIN → ADM
ALTER TYPE "CityRole" ADD VALUE 'LEAD_SUP';
ALTER TYPE "CityRole" ADD VALUE 'SUP';
ALTER TYPE "CityRole" RENAME VALUE 'CITY_ADMIN' TO 'ADM';
