/**
 * Стандартные эмодзи (имена совместимы с Rocket.Chat / emojione) + хелперы для пикера и предпросмотра.
 * В сообщение всегда вставляется :shortcode: — Rocket.Chat сам отрисует его при отправке.
 */

export interface StandardEmoji {
  /** shortcode без двоеточий */
  name: string
  /** unicode-символ */
  char: string
  /** ключевые слова (ru + en) в нижнем регистре */
  keywords: string
  /** дополнительные shortcode-алиасы */
  aliases?: string[]
  category: EmojiCategoryId
}

export type EmojiCategoryId =
  | 'smileys'
  | 'people'
  | 'nature'
  | 'food'
  | 'activities'
  | 'travel'
  | 'objects'
  | 'symbols'

export interface EmojiCategory {
  id: EmojiCategoryId
  label: string
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: 'smileys', label: 'Смайлики' },
  { id: 'people', label: 'Жесты и люди' },
  { id: 'nature', label: 'Животные и природа' },
  { id: 'food', label: 'Еда' },
  { id: 'activities', label: 'Активности' },
  { id: 'travel', label: 'Путешествия' },
  { id: 'objects', label: 'Объекты' },
  { id: 'symbols', label: 'Символы' },
]

/** [name, char, keywords, aliases?] */
type Row = [string, string, string, string[]?]

const SMILEYS: Row[] = [
  ['grinning', '😀', 'улыбка ухмылка смайлик grin smile'],
  ['smiley', '😃', 'улыбка радость happy'],
  ['smile', '😄', 'улыбка радость весело happy'],
  ['grin', '😁', 'оскал улыбка зубы'],
  ['laughing', '😆', 'смех хохот laugh', ['satisfied']],
  ['sweat_smile', '😅', 'пот неловко облегчение'],
  ['joy', '😂', 'смех слёзы ржу lol'],
  ['rofl', '🤣', 'смех катаюсь ржач', ['rolling_on_the_floor_laughing']],
  ['slight_smile', '🙂', 'улыбка лёгкая slightly smiling', ['slightly_smiling_face']],
  ['upside_down', '🙃', 'перевёрнутый ирония sarcasm', ['upside_down_face']],
  ['wink', '😉', 'подмигивание'],
  ['blush', '😊', 'смущение румянец улыбка'],
  ['innocent', '😇', 'ангел нимб невинный'],
  ['heart_eyes', '😍', 'влюблён сердечки любовь', ['smiling_face_with_heart_eyes']],
  ['star_struck', '🤩', 'восторг звёзды в глазах wow'],
  ['kissing_heart', '😘', 'поцелуй сердце kiss'],
  ['kissing', '😗', 'поцелуй'],
  ['kissing_smiling_eyes', '😙', 'поцелуй улыбка'],
  ['kissing_closed_eyes', '😚', 'поцелуй глаза закрыты'],
  ['yum', '😋', 'вкусно ням'],
  ['stuck_out_tongue', '😛', 'язык дразнить'],
  ['stuck_out_tongue_winking_eye', '😜', 'язык подмигивание шутка'],
  ['stuck_out_tongue_closed_eyes', '😝', 'язык глаза закрыты'],
  ['zany_face', '🤪', 'сумасшедший безумный'],
  ['money_mouth', '🤑', 'деньги богатство money', ['money_mouth_face']],
  ['hugging', '🤗', 'обнимашки объятия hug', ['hugging_face']],
  ['face_with_raised_eyebrow', '🤨', 'бровь сомнение скептик'],
  ['thinking', '🤔', 'думаю размышление вопрос hmm', ['thinking_face']],
  ['zipper_mouth', '🤐', 'молчу секрет рот на замке', ['zipper_mouth_face']],
  ['neutral_face', '😐', 'нейтральный без эмоций'],
  ['expressionless', '😑', 'без выражения'],
  ['no_mouth', '😶', 'молчание без рта'],
  ['smirk', '😏', 'ухмылка хитрый'],
  ['unamused', '😒', 'недоволен скучно'],
  ['roll_eyes', '🙄', 'закатил глаза ну да', ['rolling_eyes']],
  ['grimacing', '😬', 'гримаса неловко'],
  ['lying_face', '🤥', 'ложь врёт'],
  ['relieved', '😌', 'облегчение спокойствие'],
  ['pensive', '😔', 'грусть задумчивый'],
  ['sleepy', '😪', 'сонный'],
  ['sleeping', '😴', 'сон спать zzz'],
  ['drooling_face', '🤤', 'слюни хочу'],
  ['mask', '😷', 'маска болезнь'],
  ['face_with_thermometer', '🤒', 'температура болен'],
  ['face_with_head_bandage', '🤕', 'травма повязка'],
  ['nauseated_face', '🤢', 'тошнит'],
  ['face_vomiting', '🤮', 'рвота тошнит'],
  ['sneezing_face', '🤧', 'чихает насморк'],
  ['dizzy_face', '😵', 'головокружение'],
  ['exploding_head', '🤯', 'взрыв мозга шок'],
  ['cowboy', '🤠', 'ковбой шляпа', ['face_with_cowboy_hat']],
  ['sunglasses', '😎', 'крутой очки cool'],
  ['nerd', '🤓', 'ботан умник очки', ['nerd_face']],
  ['face_with_monocle', '🧐', 'монокль рассматривает'],
  ['confused', '😕', 'смущён непонимание'],
  ['worried', '😟', 'беспокойство тревога'],
  ['slight_frown', '🙁', 'грусть нахмурился', ['slightly_frowning_face']],
  ['open_mouth', '😮', 'удивление рот открыт'],
  ['hushed', '😯', 'удивлён'],
  ['astonished', '😲', 'изумление шок'],
  ['flushed', '😳', 'смущение краснеет'],
  ['frowning', '😦', 'нахмурился'],
  ['anguished', '😧', 'страдание'],
  ['fearful', '😨', 'страх боюсь'],
  ['cold_sweat', '😰', 'холодный пот тревога'],
  ['disappointed_relieved', '😥', 'разочарован облегчение'],
  ['cry', '😢', 'плач грусть слеза'],
  ['sob', '😭', 'рыдает слёзы'],
  ['scream', '😱', 'крик ужас'],
  ['confounded', '😖', 'расстроен'],
  ['persevere', '😣', 'стараюсь терплю'],
  ['disappointed', '😞', 'разочарование грусть'],
  ['sweat', '😓', 'пот усталость'],
  ['weary', '😩', 'устал измотан'],
  ['tired_face', '😫', 'устал'],
  ['triumph', '😤', 'триумф упрямство пар из носа'],
  ['rage', '😡', 'ярость злой'],
  ['angry', '😠', 'злой сердитый'],
  ['face_with_symbols_over_mouth', '🤬', 'ругань мат злость'],
  ['smiling_imp', '😈', 'чертёнок злодей'],
  ['imp', '👿', 'злой чёрт'],
  ['skull', '💀', 'череп смерть'],
  ['poop', '💩', 'какашка', ['hankey', 'poo']],
  ['clown', '🤡', 'клоун', ['clown_face']],
  ['japanese_ogre', '👹', 'демон огр'],
  ['ghost', '👻', 'привидение призрак'],
  ['alien', '👽', 'инопланетянин нло'],
  ['robot', '🤖', 'робот бот', ['robot_face']],
  ['smiley_cat', '😺', 'кот улыбка'],
  ['heart_eyes_cat', '😻', 'кот влюблён'],
  ['joy_cat', '😹', 'кот смех'],
  ['crying_cat_face', '😿', 'кот плачет'],
  ['see_no_evil', '🙈', 'обезьяна не вижу'],
  ['hear_no_evil', '🙉', 'обезьяна не слышу'],
  ['speak_no_evil', '🙊', 'обезьяна не скажу'],
  ['relaxed', '☺️', 'улыбка спокойствие'],
  ['face_palm', '🤦', 'фейспалм рукалицо', ['facepalm']],
  ['shrug', '🤷', 'пожимает плечами не знаю'],
]

const PEOPLE: Row[] = [
  ['wave', '👋', 'привет пока машет hello bye'],
  ['raised_back_of_hand', '🤚', 'рука тыльная сторона'],
  ['hand_splayed', '🖐', 'рука пальцы раскрыты', ['raised_hand_with_fingers_splayed']],
  ['raised_hand', '✋', 'рука стоп хай файв high five', ['hand']],
  ['vulcan', '🖖', 'вулканский салют', ['vulcan_salute']],
  ['ok_hand', '👌', 'ок отлично хорошо okay'],
  ['v', '✌️', 'победа мир два пальца victory'],
  ['fingers_crossed', '🤞', 'скрестил пальцы удача', ['crossed_fingers']],
  ['love_you_gesture', '🤟', 'люблю жест'],
  ['metal', '🤘', 'рок коза', ['sign_of_the_horns']],
  ['call_me', '🤙', 'позвони шака', ['call_me_hand']],
  ['point_left', '👈', 'налево указывает'],
  ['point_right', '👉', 'направо указывает'],
  ['point_up_2', '👆', 'вверх указывает'],
  ['point_down', '👇', 'вниз указывает'],
  ['point_up', '☝️', 'вверх палец внимание'],
  ['thumbsup', '👍', 'класс лайк одобрение да like yes', ['+1', 'thumbup', 'thumbs_up']],
  ['thumbsdown', '👎', 'дизлайк нет против dislike no', ['-1', 'thumbdown', 'thumbs_down']],
  ['fist', '✊', 'кулак сила', ['fist_raised']],
  ['punch', '👊', 'кулак удар', ['fist_oncoming']],
  ['left_facing_fist', '🤛', 'кулак влево'],
  ['right_facing_fist', '🤜', 'кулак вправо'],
  ['clap', '👏', 'аплодисменты браво хлопаю bravo'],
  ['raised_hands', '🙌', 'ура руки вверх победа hooray'],
  ['open_hands', '👐', 'открытые руки'],
  ['palms_up_together', '🤲', 'ладони вместе'],
  ['handshake', '🤝', 'рукопожатие договорились сделка deal'],
  ['pray', '🙏', 'спасибо пожалуйста молитва прошу please thanks'],
  ['writing_hand', '✍️', 'пишет рука писать'],
  ['nail_care', '💅', 'маникюр ногти'],
  ['selfie', '🤳', 'селфи'],
  ['muscle', '💪', 'сила мышцы бицепс strong'],
  ['ear', '👂', 'ухо слушать'],
  ['nose', '👃', 'нос'],
  ['eyes', '👀', 'глаза смотрю внимание look'],
  ['eye', '👁', 'глаз'],
  ['tongue', '👅', 'язык'],
  ['lips', '👄', 'губы рот'],
  ['brain', '🧠', 'мозг ум'],
  ['baby', '👶', 'малыш ребёнок'],
  ['boy', '👦', 'мальчик'],
  ['girl', '👧', 'девочка'],
  ['man', '👨', 'мужчина'],
  ['woman', '👩', 'женщина'],
  ['older_man', '👴', 'дедушка пожилой мужчина'],
  ['older_woman', '👵', 'бабушка пожилая женщина'],
  ['no_good', '🙅', 'нет нельзя запрет'],
  ['ok_woman', '🙆', 'ок жест'],
  ['information_desk_person', '💁', 'справка подсказка'],
  ['raising_hand', '🙋', 'вопрос поднял руку'],
  ['bow', '🙇', 'поклон извините'],
  ['cop', '👮', 'полиция'],
  ['guardsman', '💂', 'гвардеец стража'],
  ['detective', '🕵', 'детектив сыщик'],
  ['construction_worker', '👷', 'строитель каска'],
  ['princess', '👸', 'принцесса'],
  ['santa', '🎅', 'дед мороз санта'],
  ['angel', '👼', 'ангел'],
  ['runner', '🏃', 'бегун бег'],
  ['dancer', '💃', 'танцует танцы'],
  ['man_dancing', '🕺', 'танцует мужчина'],
  ['couple', '👫', 'пара'],
  ['family', '👪', 'семья'],
  ['couplekiss', '💏', 'поцелуй пара'],
  ['couple_with_heart', '💑', 'пара любовь'],
  ['footprints', '👣', 'следы шаги'],
  ['bust_in_silhouette', '👤', 'силуэт пользователь user'],
  ['busts_in_silhouette', '👥', 'силуэты пользователи команда users team'],
  ['speaking_head', '🗣', 'говорит голова'],
]

const NATURE: Row[] = [
  ['dog', '🐶', 'собака пёс'],
  ['cat', '🐱', 'кот кошка'],
  ['mouse', '🐭', 'мышь'],
  ['hamster', '🐹', 'хомяк'],
  ['rabbit', '🐰', 'кролик заяц'],
  ['fox', '🦊', 'лиса', ['fox_face']],
  ['bear', '🐻', 'медведь'],
  ['panda_face', '🐼', 'панда'],
  ['koala', '🐨', 'коала'],
  ['tiger', '🐯', 'тигр'],
  ['lion_face', '🦁', 'лев', ['lion']],
  ['cow', '🐮', 'корова'],
  ['pig', '🐷', 'свинья'],
  ['frog', '🐸', 'лягушка жаба'],
  ['monkey_face', '🐵', 'обезьяна'],
  ['monkey', '🐒', 'обезьяна'],
  ['chicken', '🐔', 'курица'],
  ['penguin', '🐧', 'пингвин'],
  ['bird', '🐦', 'птица'],
  ['baby_chick', '🐤', 'цыплёнок'],
  ['hatching_chick', '🐣', 'цыплёнок вылупился'],
  ['hatched_chick', '🐥', 'цыплёнок'],
  ['duck', '🦆', 'утка'],
  ['eagle', '🦅', 'орёл'],
  ['owl', '🦉', 'сова'],
  ['bat', '🦇', 'летучая мышь'],
  ['wolf', '🐺', 'волк'],
  ['boar', '🐗', 'кабан'],
  ['horse', '🐴', 'лошадь конь'],
  ['unicorn', '🦄', 'единорог', ['unicorn_face']],
  ['bee', '🐝', 'пчела', ['honeybee']],
  ['bug', '🐛', 'гусеница баг жук'],
  ['butterfly', '🦋', 'бабочка'],
  ['snail', '🐌', 'улитка медленно'],
  ['shell', '🐚', 'ракушка'],
  ['beetle', '🐞', 'божья коровка', ['lady_beetle']],
  ['ant', '🐜', 'муравей'],
  ['spider', '🕷', 'паук'],
  ['spider_web', '🕸', 'паутина'],
  ['scorpion', '🦂', 'скорпион'],
  ['turtle', '🐢', 'черепаха'],
  ['snake', '🐍', 'змея python питон'],
  ['lizard', '🦎', 'ящерица'],
  ['t_rex', '🦖', 'динозавр тирекс'],
  ['sauropod', '🦕', 'динозавр'],
  ['octopus', '🐙', 'осьминог'],
  ['squid', '🦑', 'кальмар'],
  ['shrimp', '🦐', 'креветка'],
  ['crab', '🦀', 'краб'],
  ['blowfish', '🐡', 'фугу рыба'],
  ['tropical_fish', '🐠', 'рыбка тропическая'],
  ['fish', '🐟', 'рыба'],
  ['dolphin', '🐬', 'дельфин', ['flipper']],
  ['whale', '🐳', 'кит'],
  ['whale2', '🐋', 'кит'],
  ['shark', '🦈', 'акула'],
  ['crocodile', '🐊', 'крокодил'],
  ['leopard', '🐆', 'леопард'],
  ['zebra', '🦓', 'зебра'],
  ['gorilla', '🦍', 'горилла'],
  ['elephant', '🐘', 'слон'],
  ['rhino', '🦏', 'носорог', ['rhinoceros']],
  ['camel', '🐪', 'верблюд'],
  ['giraffe', '🦒', 'жираф'],
  ['buffalo', '🐃', 'буйвол'],
  ['ox', '🐂', 'бык'],
  ['cow2', '🐄', 'корова'],
  ['racehorse', '🐎', 'скакун лошадь'],
  ['pig2', '🐖', 'свинья'],
  ['ram', '🐏', 'баран'],
  ['sheep', '🐑', 'овца'],
  ['goat', '🐐', 'коза'],
  ['dromedary_camel', '🐫', 'верблюд'],
  ['dog2', '🐕', 'собака'],
  ['poodle', '🐩', 'пудель'],
  ['cat2', '🐈', 'кошка'],
  ['rooster', '🐓', 'петух'],
  ['turkey', '🦃', 'индейка'],
  ['dove', '🕊', 'голубь мир', ['dove_of_peace']],
  ['rabbit2', '🐇', 'кролик'],
  ['mouse2', '🐁', 'мышь'],
  ['rat', '🐀', 'крыса'],
  ['chipmunk', '🐿', 'бурундук белка'],
  ['hedgehog', '🦔', 'ёж'],
  ['paw_prints', '🐾', 'лапы следы'],
  ['dragon', '🐉', 'дракон'],
  ['dragon_face', '🐲', 'дракон'],
  ['cactus', '🌵', 'кактус'],
  ['christmas_tree', '🎄', 'ёлка новый год рождество'],
  ['evergreen_tree', '🌲', 'ель сосна'],
  ['deciduous_tree', '🌳', 'дерево'],
  ['palm_tree', '🌴', 'пальма'],
  ['seedling', '🌱', 'росток рост'],
  ['herb', '🌿', 'трава растение'],
  ['shamrock', '☘️', 'клевер'],
  ['four_leaf_clover', '🍀', 'клевер удача'],
  ['maple_leaf', '🍁', 'лист клён осень'],
  ['fallen_leaf', '🍂', 'опавший лист осень'],
  ['leaves', '🍃', 'листья ветер'],
  ['mushroom', '🍄', 'гриб'],
  ['bouquet', '💐', 'букет цветы'],
  ['tulip', '🌷', 'тюльпан'],
  ['rose', '🌹', 'роза цветок'],
  ['wilted_rose', '🥀', 'увядшая роза', ['wilted_flower']],
  ['hibiscus', '🌺', 'гибискус цветок'],
  ['cherry_blossom', '🌸', 'сакура цветок'],
  ['blossom', '🌼', 'цветок'],
  ['sunflower', '🌻', 'подсолнух'],
  ['sun_with_face', '🌞', 'солнце лицо'],
  ['full_moon_with_face', '🌝', 'луна лицо'],
  ['new_moon_with_face', '🌚', 'новолуние лицо'],
  ['crescent_moon', '🌙', 'месяц ночь'],
  ['earth_africa', '🌍', 'земля планета мир'],
  ['earth_americas', '🌎', 'земля планета'],
  ['earth_asia', '🌏', 'земля планета'],
  ['sunny', '☀️', 'солнце погода ясно'],
  ['partly_sunny', '⛅', 'облачно солнце погода'],
  ['cloud', '☁️', 'облако'],
  ['cloud_rain', '🌧', 'дождь', ['cloud_with_rain']],
  ['thunder_cloud_rain', '⛈', 'гроза', ['cloud_with_lightning_and_rain']],
  ['zap', '⚡', 'молния электричество быстро lightning'],
  ['snowflake', '❄️', 'снежинка снег холод'],
  ['snowman', '⛄', 'снеговик'],
  ['fire', '🔥', 'огонь пламя горячо круто hot'],
  ['droplet', '💧', 'капля вода'],
  ['ocean', '🌊', 'волна океан море'],
  ['rainbow', '🌈', 'радуга'],
  ['star2', '🌟', 'звезда сияющая', ['glowing_star']],
  ['sparkles', '✨', 'искры блеск магия новое'],
  ['comet', '☄️', 'комета'],
  ['volcano', '🌋', 'вулкан'],
  ['umbrella2', '☂️', 'зонт дождь'],
]

const FOOD: Row[] = [
  ['apple', '🍎', 'яблоко красное', ['red_apple']],
  ['green_apple', '🍏', 'яблоко зелёное'],
  ['pear', '🍐', 'груша'],
  ['tangerine', '🍊', 'апельсин мандарин'],
  ['lemon', '🍋', 'лимон'],
  ['banana', '🍌', 'банан'],
  ['watermelon', '🍉', 'арбуз'],
  ['grapes', '🍇', 'виноград'],
  ['strawberry', '🍓', 'клубника'],
  ['melon', '🍈', 'дыня'],
  ['cherries', '🍒', 'вишня черешня'],
  ['peach', '🍑', 'персик'],
  ['pineapple', '🍍', 'ананас'],
  ['kiwi', '🥝', 'киви', ['kiwifruit']],
  ['avocado', '🥑', 'авокадо'],
  ['tomato', '🍅', 'помидор томат'],
  ['eggplant', '🍆', 'баклажан'],
  ['cucumber', '🥒', 'огурец'],
  ['carrot', '🥕', 'морковь'],
  ['corn', '🌽', 'кукуруза'],
  ['hot_pepper', '🌶', 'перец острый'],
  ['potato', '🥔', 'картошка картофель'],
  ['sweet_potato', '🍠', 'батат'],
  ['chestnut', '🌰', 'каштан'],
  ['peanuts', '🥜', 'арахис орехи'],
  ['bread', '🍞', 'хлеб'],
  ['croissant', '🥐', 'круассан'],
  ['baguette_bread', '🥖', 'багет'],
  ['pretzel', '🥨', 'крендель'],
  ['pancakes', '🥞', 'блины панкейки'],
  ['cheese', '🧀', 'сыр', ['cheese_wedge']],
  ['meat_on_bone', '🍖', 'мясо'],
  ['poultry_leg', '🍗', 'курица ножка'],
  ['bacon', '🥓', 'бекон'],
  ['hamburger', '🍔', 'бургер гамбургер'],
  ['fries', '🍟', 'картошка фри'],
  ['pizza', '🍕', 'пицца'],
  ['hotdog', '🌭', 'хот-дог'],
  ['sandwich', '🥪', 'сэндвич бутерброд'],
  ['taco', '🌮', 'тако'],
  ['burrito', '🌯', 'буррито'],
  ['egg', '🥚', 'яйцо'],
  ['cooking', '🍳', 'яичница жарить сковорода'],
  ['stew', '🥘', 'рагу блюдо'],
  ['salad', '🥗', 'салат', ['green_salad']],
  ['popcorn', '🍿', 'попкорн кино'],
  ['bento', '🍱', 'бенто'],
  ['rice_cracker', '🍘', 'рисовый крекер'],
  ['rice_ball', '🍙', 'онигири рис'],
  ['rice', '🍚', 'рис'],
  ['curry', '🍛', 'карри'],
  ['ramen', '🍜', 'рамен лапша'],
  ['spaghetti', '🍝', 'спагетти паста'],
  ['sushi', '🍣', 'суши'],
  ['fried_shrimp', '🍤', 'креветка тэмпура'],
  ['fish_cake', '🍥', 'рыбный торт'],
  ['dumpling', '🥟', 'пельмени вареники'],
  ['oden', '🍢', 'одэн'],
  ['dango', '🍡', 'данго'],
  ['icecream', '🍦', 'мороженое'],
  ['shaved_ice', '🍧', 'ледяная крошка'],
  ['ice_cream', '🍨', 'мороженое'],
  ['doughnut', '🍩', 'пончик'],
  ['cookie', '🍪', 'печенье'],
  ['birthday', '🎂', 'торт день рождения'],
  ['cake', '🍰', 'торт кусок пирожное'],
  ['chocolate_bar', '🍫', 'шоколад'],
  ['candy', '🍬', 'конфета'],
  ['lollipop', '🍭', 'леденец'],
  ['custard', '🍮', 'пудинг'],
  ['honey_pot', '🍯', 'мёд'],
  ['baby_bottle', '🍼', 'бутылочка молоко'],
  ['milk', '🥛', 'молоко стакан', ['glass_of_milk']],
  ['coffee', '☕', 'кофе чашка перерыв'],
  ['tea', '🍵', 'чай'],
  ['sake', '🍶', 'саке'],
  ['champagne', '🍾', 'шампанское праздник'],
  ['wine_glass', '🍷', 'вино бокал'],
  ['cocktail', '🍸', 'коктейль'],
  ['tropical_drink', '🍹', 'напиток коктейль'],
  ['beer', '🍺', 'пиво'],
  ['beers', '🍻', 'пиво кружки чокнуться'],
  ['clinking_glass', '🥂', 'бокалы тост', ['champagne_glass']],
  ['tumbler_glass', '🥃', 'виски стакан'],
  ['fork_and_knife', '🍴', 'вилка нож обед еда'],
  ['spoon', '🥄', 'ложка'],
  ['chopsticks', '🥢', 'палочки'],
]

const ACTIVITIES: Row[] = [
  ['soccer', '⚽', 'футбол мяч'],
  ['basketball', '🏀', 'баскетбол мяч'],
  ['football', '🏈', 'американский футбол'],
  ['baseball', '⚾', 'бейсбол'],
  ['tennis', '🎾', 'теннис'],
  ['volleyball', '🏐', 'волейбол'],
  ['rugby_football', '🏉', 'регби'],
  ['8ball', '🎱', 'бильярд'],
  ['ping_pong', '🏓', 'пинг-понг настольный теннис', ['table_tennis']],
  ['badminton', '🏸', 'бадминтон'],
  ['hockey', '🏒', 'хоккей'],
  ['golf', '⛳', 'гольф'],
  ['bow_and_arrow', '🏹', 'лук стрелы', ['archery']],
  ['fishing_pole_and_fish', '🎣', 'рыбалка'],
  ['boxing_glove', '🥊', 'бокс перчатка'],
  ['martial_arts_uniform', '🥋', 'кимоно единоборства'],
  ['ice_skate', '⛸', 'коньки'],
  ['ski', '🎿', 'лыжи'],
  ['skier', '⛷', 'лыжник'],
  ['snowboarder', '🏂', 'сноуборд'],
  ['weight_lifter', '🏋', 'штанга тренировка'],
  ['surfer', '🏄', 'сёрфинг'],
  ['swimmer', '🏊', 'плавание'],
  ['bicyclist', '🚴', 'велосипед спорт'],
  ['trophy', '🏆', 'кубок победа награда трофей'],
  ['medal', '🏅', 'медаль', ['sports_medal']],
  ['first_place', '🥇', 'первое место золото', ['first_place_medal']],
  ['second_place', '🥈', 'второе место серебро', ['second_place_medal']],
  ['third_place', '🥉', 'третье место бронза', ['third_place_medal']],
  ['reminder_ribbon', '🎗', 'лента напоминание'],
  ['dart', '🎯', 'мишень цель дартс target'],
  ['video_game', '🎮', 'игра геймпад приставка game'],
  ['joystick', '🕹', 'джойстик'],
  ['slot_machine', '🎰', 'казино автомат'],
  ['game_die', '🎲', 'кубик игра'],
  ['jigsaw', '🧩', 'пазл головоломка'],
  ['performing_arts', '🎭', 'театр маски'],
  ['art', '🎨', 'палитра искусство рисовать дизайн'],
  ['tada', '🎉', 'праздник поздравляю ура хлопушка congrats party'],
  ['confetti_ball', '🎊', 'конфетти праздник'],
  ['balloon', '🎈', 'шарик праздник'],
  ['gift', '🎁', 'подарок'],
  ['ticket', '🎫', 'билет'],
  ['circus_tent', '🎪', 'цирк шатёр'],
  ['clapper', '🎬', 'хлопушка кино съёмка'],
  ['microphone', '🎤', 'микрофон караоке'],
  ['headphones', '🎧', 'наушники музыка'],
  ['musical_note', '🎵', 'нота музыка'],
  ['notes', '🎶', 'ноты музыка'],
  ['musical_score', '🎼', 'партитура ноты'],
  ['musical_keyboard', '🎹', 'пианино клавиши'],
  ['guitar', '🎸', 'гитара'],
  ['violin', '🎻', 'скрипка'],
  ['trumpet', '🎺', 'труба'],
  ['saxophone', '🎷', 'саксофон'],
  ['drum', '🥁', 'барабан', ['drum_with_drumsticks']],
  ['fireworks', '🎆', 'салют фейерверк'],
  ['sparkler', '🎇', 'бенгальский огонь'],
  ['ferris_wheel', '🎡', 'колесо обозрения'],
  ['roller_coaster', '🎢', 'американские горки'],
  ['crystal_ball', '🔮', 'хрустальный шар предсказание'],
  ['bowling', '🎳', 'боулинг'],
  ['flower_playing_cards', '🎴', 'карты цветы'],
  ['mahjong', '🀄', 'маджонг'],
  ['crossed_flags', '🎌', 'флаги'],
  ['checkered_flag', '🏁', 'финиш флаг гонка'],
  ['triangular_flag_on_post', '🚩', 'флажок красный флаг'],
  ['white_flag', '🏳', 'белый флаг'],
  ['chess_pawn', '♟', 'шахматы пешка'],
]

const CLOCK_ROWS: Row[] = [
  ['clock1', '🕐', 'часы 1 час время'],
  ['clock2', '🕑', 'часы 2 часа время'],
  ['clock3', '🕒', 'часы 3 часа время'],
  ['clock4', '🕓', 'часы 4 часа время'],
  ['clock5', '🕔', 'часы 5 часов время'],
  ['clock6', '🕕', 'часы 6 часов время'],
  ['clock7', '🕖', 'часы 7 часов время'],
  ['clock8', '🕗', 'часы 8 часов время'],
  ['clock9', '🕘', 'часы 9 часов время'],
  ['clock10', '🕙', 'часы 10 часов время'],
  ['clock11', '🕚', 'часы 11 часов время'],
  ['clock12', '🕛', 'часы 12 часов время'],
  ['clock130', '🕜', 'часы 1:30 время'],
  ['clock230', '🕝', 'часы 2:30 время'],
  ['clock330', '🕞', 'часы 3:30 время'],
  ['clock430', '🕟', 'часы 4:30 время'],
  ['clock530', '🕠', 'часы 5:30 время'],
  ['clock630', '🕡', 'часы 6:30 время'],
  ['clock730', '🕢', 'часы 7:30 время'],
  ['clock830', '🕣', 'часы 8:30 время'],
  ['clock930', '🕤', 'часы 9:30 время'],
  ['clock1030', '🕥', 'часы 10:30 время'],
  ['clock1130', '🕦', 'часы 11:30 время'],
  ['clock1230', '🕧', 'часы 12:30 время'],
]

const TRAVEL: Row[] = [
  ['rocket', '🚀', 'ракета запуск старт релиз космос launch'],
  ['flying_saucer', '🛸', 'нло тарелка'],
  ['satellite_orbital', '🛰', 'спутник', ['artificial_satellite']],
  ['airplane', '✈️', 'самолёт полёт'],
  ['small_airplane', '🛩', 'самолёт маленький'],
  ['helicopter', '🚁', 'вертолёт'],
  ['car', '🚗', 'машина автомобиль', ['red_car']],
  ['taxi', '🚕', 'такси'],
  ['blue_car', '🚙', 'машина внедорожник'],
  ['bus', '🚌', 'автобус'],
  ['trolleybus', '🚎', 'троллейбус'],
  ['race_car', '🏎', 'гоночная машина', ['racing_car']],
  ['police_car', '🚓', 'полицейская машина'],
  ['ambulance', '🚑', 'скорая помощь'],
  ['fire_engine', '🚒', 'пожарная машина'],
  ['minibus', '🚐', 'микроавтобус'],
  ['truck', '🚚', 'грузовик доставка'],
  ['articulated_lorry', '🚛', 'фура грузовик'],
  ['tractor', '🚜', 'трактор'],
  ['motorcycle', '🏍', 'мотоцикл', ['racing_motorcycle']],
  ['bike', '🚲', 'велосипед'],
  ['scooter', '🛴', 'самокат'],
  ['sailboat', '⛵', 'парусник яхта', ['boat']],
  ['speedboat', '🚤', 'катер'],
  ['ship', '🚢', 'корабль'],
  ['anchor', '⚓', 'якорь'],
  ['train', '🚆', 'поезд', ['train2']],
  ['bullettrain_side', '🚄', 'скоростной поезд'],
  ['bullettrain_front', '🚅', 'скоростной поезд'],
  ['metro', '🚇', 'метро'],
  ['light_rail', '🚈', 'легкорельсовый'],
  ['station', '🚉', 'станция вокзал'],
  ['tram', '🚊', 'трамвай'],
  ['monorail', '🚝', 'монорельс'],
  ['fuelpump', '⛽', 'заправка бензин'],
  ['rotating_light', '🚨', 'мигалка сирена тревога авария alert'],
  ['traffic_light', '🚥', 'светофор'],
  ['vertical_traffic_light', '🚦', 'светофор'],
  ['construction', '🚧', 'ремонт стройка работы'],
  ['house', '🏠', 'дом'],
  ['house_with_garden', '🏡', 'дом с садом'],
  ['office', '🏢', 'офис здание'],
  ['post_office', '🏣', 'почта'],
  ['hospital', '🏥', 'больница'],
  ['bank', '🏦', 'банк'],
  ['hotel', '🏨', 'отель'],
  ['school', '🏫', 'школа'],
  ['department_store', '🏬', 'универмаг магазин'],
  ['factory', '🏭', 'завод фабрика'],
  ['european_castle', '🏰', 'замок'],
  ['japanese_castle', '🏯', 'замок японский'],
  ['stadium', '🏟', 'стадион'],
  ['statue_of_liberty', '🗽', 'статуя свободы'],
  ['tokyo_tower', '🗼', 'токийская башня'],
  ['church', '⛪', 'церковь'],
  ['mosque', '🕌', 'мечеть'],
  ['fountain', '⛲', 'фонтан'],
  ['tent', '⛺', 'палатка кемпинг'],
  ['foggy', '🌁', 'туман'],
  ['night_with_stars', '🌃', 'ночь город звёзды'],
  ['cityscape', '🏙', 'город'],
  ['sunrise_over_mountains', '🌄', 'рассвет горы'],
  ['sunrise', '🌅', 'рассвет'],
  ['city_sunset', '🌆', 'закат город'],
  ['city_dusk', '🌇', 'закат'],
  ['bridge_at_night', '🌉', 'мост ночью'],
  ['map', '🗺', 'карта', ['world_map']],
  ['compass', '🧭', 'компас навигация'],
  ['mountain', '⛰', 'гора'],
  ['mount_fuji', '🗻', 'фудзи гора'],
  ['camping', '🏕', 'кемпинг'],
  ['beach_with_umbrella', '🏖', 'пляж отпуск', ['beach']],
  ['desert', '🏜', 'пустыня'],
  ['island', '🏝', 'остров', ['desert_island']],
  ['national_park', '🏞', 'национальный парк'],
  ['hourglass', '⌛', 'песочные часы время ожидание'],
  ['hourglass_flowing_sand', '⏳', 'песочные часы ожидание подождите'],
  ['watch', '⌚', 'часы наручные'],
  ['alarm_clock', '⏰', 'будильник время срок deadline'],
  ['stopwatch', '⏱', 'секундомер'],
  ['timer', '⏲', 'таймер', ['timer_clock']],
  ['clock', '🕰', 'часы настольные', ['mantlepiece_clock']],
  ...CLOCK_ROWS,
]

const OBJECTS: Row[] = [
  ['bulb', '💡', 'лампочка идея свет idea'],
  ['flashlight', '🔦', 'фонарик'],
  ['calendar', '📅', 'календарь дата расписание'],
  ['date', '📆', 'календарь отрывной'],
  ['calendar_spiral', '🗓', 'календарь планирование', ['spiral_calendar_pad']],
  ['bell', '🔔', 'колокольчик уведомление notification'],
  ['no_bell', '🔕', 'без звука уведомления выключены'],
  ['mega', '📣', 'рупор объявление', ['megaphone']],
  ['loudspeaker', '📢', 'громкоговоритель объявление важно'],
  ['books', '📚', 'книги учёба материалы'],
  ['book', '📖', 'книга открытая', ['open_book']],
  ['closed_book', '📕', 'книга красная'],
  ['green_book', '📗', 'книга зелёная'],
  ['blue_book', '📘', 'книга синяя'],
  ['orange_book', '📙', 'книга оранжевая'],
  ['notebook', '📓', 'блокнот тетрадь'],
  ['ledger', '📒', 'учётная книга'],
  ['page_facing_up', '📄', 'документ страница файл'],
  ['page_with_curl', '📃', 'документ страница'],
  ['bookmark_tabs', '📑', 'закладки вкладки'],
  ['bookmark', '🔖', 'закладка'],
  ['label', '🏷', 'ярлык метка тег'],
  ['newspaper', '📰', 'газета новости'],
  ['rolled_up_newspaper', '🗞', 'газета', ['newspaper2']],
  ['memo', '📝', 'заметка записка письмо', ['pencil']],
  ['pencil2', '✏️', 'карандаш'],
  ['pen_ballpoint', '🖊', 'ручка', ['lower_left_ballpoint_pen']],
  ['paintbrush', '🖌', 'кисть', ['lower_left_paintbrush']],
  ['crayon', '🖍', 'мелок', ['lower_left_crayon']],
  ['scissors', '✂️', 'ножницы'],
  ['paperclip', '📎', 'скрепка вложение'],
  ['paperclips', '🖇', 'скрепки', ['linked_paperclips']],
  ['pushpin', '📌', 'кнопка закрепить'],
  ['round_pushpin', '📍', 'метка место локация'],
  ['straight_ruler', '📏', 'линейка'],
  ['triangular_ruler', '📐', 'угольник'],
  ['file_folder', '📁', 'папка'],
  ['open_file_folder', '📂', 'папка открытая'],
  ['dividers', '🗂', 'разделители картотека', ['card_index_dividers']],
  ['clipboard', '📋', 'буфер обмена список чеклист'],
  ['card_index', '📇', 'картотека визитки'],
  ['chart_with_upwards_trend', '📈', 'график рост'],
  ['chart_with_downwards_trend', '📉', 'график падение'],
  ['bar_chart', '📊', 'диаграмма статистика'],
  ['file_cabinet', '🗄', 'шкаф архив'],
  ['wastebasket', '🗑', 'корзина удалить'],
  ['lock', '🔒', 'замок закрыто безопасность'],
  ['unlock', '🔓', 'замок открыт'],
  ['lock_with_ink_pen', '🔏', 'замок с пером'],
  ['closed_lock_with_key', '🔐', 'замок с ключом'],
  ['key', '🔑', 'ключ пароль'],
  ['old_key', '🗝', 'старый ключ', ['key2']],
  ['hammer', '🔨', 'молоток'],
  ['pick', '⛏', 'кирка'],
  ['hammer_and_wrench', '🛠', 'инструменты ремонт настройка', ['tools']],
  ['wrench', '🔧', 'гаечный ключ'],
  ['nut_and_bolt', '🔩', 'болт гайка'],
  ['gear', '⚙️', 'шестерёнка настройки settings'],
  ['link', '🔗', 'ссылка'],
  ['chains', '⛓', 'цепи'],
  ['shield', '🛡', 'щит защита'],
  ['mag', '🔍', 'поиск лупа search'],
  ['mag_right', '🔎', 'поиск лупа'],
  ['telephone', '☎️', 'телефон'],
  ['telephone_receiver', '📞', 'трубка звонок'],
  ['iphone', '📱', 'телефон смартфон мобильный'],
  ['calling', '📲', 'звонок телефон'],
  ['computer', '💻', 'ноутбук компьютер'],
  ['desktop', '🖥', 'компьютер монитор', ['desktop_computer']],
  ['keyboard', '⌨️', 'клавиатура'],
  ['printer', '🖨', 'принтер'],
  ['mouse_three_button', '🖱', 'мышка компьютерная', ['three_button_mouse']],
  ['minidisc', '💽', 'диск'],
  ['floppy_disk', '💾', 'дискета сохранить save'],
  ['cd', '💿', 'диск cd'],
  ['dvd', '📀', 'диск dvd'],
  ['tv', '📺', 'телевизор'],
  ['camera', '📷', 'камера фото'],
  ['camera_with_flash', '📸', 'фото вспышка'],
  ['video_camera', '📹', 'видеокамера'],
  ['movie_camera', '🎥', 'кинокамера видео'],
  ['film_projector', '📽', 'проектор'],
  ['radio', '📻', 'радио'],
  ['battery', '🔋', 'батарея'],
  ['electric_plug', '🔌', 'вилка розетка'],
  ['email', '📧', 'почта письмо email', ['e-mail']],
  ['envelope', '✉️', 'конверт письмо'],
  ['envelope_with_arrow', '📩', 'письмо отправлено'],
  ['incoming_envelope', '📨', 'входящее письмо'],
  ['mailbox', '📫', 'почтовый ящик'],
  ['inbox_tray', '📥', 'входящие'],
  ['outbox_tray', '📤', 'исходящие'],
  ['package', '📦', 'посылка коробка пакет'],
  ['postbox', '📮', 'почтовый ящик'],
  ['moneybag', '💰', 'деньги мешок'],
  ['dollar', '💵', 'доллар деньги'],
  ['euro', '💶', 'евро деньги'],
  ['yen', '💴', 'йена деньги'],
  ['pound', '💷', 'фунт деньги'],
  ['credit_card', '💳', 'карта оплата'],
  ['gem', '💎', 'бриллиант драгоценность'],
  ['scales', '⚖', 'весы справедливость', ['balance_scale']],
  ['microscope', '🔬', 'микроскоп наука'],
  ['telescope', '🔭', 'телескоп'],
  ['satellite', '📡', 'спутниковая антенна'],
  ['syringe', '💉', 'шприц прививка'],
  ['pill', '💊', 'таблетка лекарство'],
  ['thermometer', '🌡', 'термометр температура'],
  ['door', '🚪', 'дверь'],
  ['bed', '🛏', 'кровать'],
  ['couch', '🛋', 'диван', ['couch_and_lamp']],
  ['toilet', '🚽', 'туалет'],
  ['shower', '🚿', 'душ'],
  ['bathtub', '🛁', 'ванна'],
  ['shopping_cart', '🛒', 'корзина покупки', ['shopping_trolley']],
  ['crown', '👑', 'корона'],
  ['tophat', '🎩', 'цилиндр шляпа'],
  ['mortar_board', '🎓', 'выпускник шапочка учёба'],
  ['necktie', '👔', 'галстук рубашка'],
  ['shirt', '👕', 'футболка', ['tshirt']],
  ['jeans', '👖', 'джинсы'],
  ['dress', '👗', 'платье'],
  ['bikini', '👙', 'купальник'],
  ['handbag', '👜', 'сумка'],
  ['school_satchel', '🎒', 'рюкзак портфель'],
  ['eyeglasses', '👓', 'очки'],
  ['dark_sunglasses', '🕶', 'солнечные очки'],
  ['ring', '💍', 'кольцо'],
  ['lipstick', '💄', 'помада'],
  ['bomb', '💣', 'бомба'],
  ['boom', '💥', 'взрыв бум', ['collision']],
  ['speech_balloon', '💬', 'комментарий сообщение чат'],
  ['thought_balloon', '💭', 'мысль облачко'],
  ['zzz', '💤', 'сон zzz'],
  ['candle', '🕯', 'свеча'],
  ['microphone2', '🎙', 'студийный микрофон', ['studio_microphone']],
  ['pager', '📟', 'пейджер'],
  ['fax', '📠', 'факс'],
  ['teddy_bear', '🧸', 'плюшевый мишка'],
  ['moyai', '🗿', 'моаи статуя'],
]

const SYMBOLS: Row[] = [
  ['heart', '❤️', 'сердце любовь красное love'],
  ['orange_heart', '🧡', 'сердце оранжевое'],
  ['yellow_heart', '💛', 'сердце жёлтое'],
  ['green_heart', '💚', 'сердце зелёное'],
  ['blue_heart', '💙', 'сердце синее'],
  ['purple_heart', '💜', 'сердце фиолетовое'],
  ['black_heart', '🖤', 'сердце чёрное'],
  ['broken_heart', '💔', 'разбитое сердце'],
  ['heart_exclamation', '❣️', 'сердце восклицание', ['heavy_heart_exclamation_mark_ornament']],
  ['two_hearts', '💕', 'два сердца'],
  ['revolving_hearts', '💞', 'сердца'],
  ['heartbeat', '💓', 'сердцебиение'],
  ['heartpulse', '💗', 'сердце растёт'],
  ['sparkling_heart', '💖', 'сердце блестит'],
  ['cupid', '💘', 'сердце стрела амур'],
  ['gift_heart', '💝', 'сердце подарок'],
  ['heart_decoration', '💟', 'сердце украшение'],
  ['peace', '☮️', 'мир', ['peace_symbol']],
  ['100', '💯', 'сто баллов отлично идеально'],
  ['anger', '💢', 'злость'],
  ['white_check_mark', '✅', 'галочка готово выполнено да ok done'],
  ['ballot_box_with_check', '☑️', 'галочка чекбокс'],
  ['heavy_check_mark', '✔️', 'галочка'],
  ['x', '❌', 'крестик нет ошибка неверно wrong'],
  ['negative_squared_cross_mark', '❎', 'крестик квадрат'],
  ['heavy_multiplication_x', '✖️', 'умножить крест'],
  ['heavy_plus_sign', '➕', 'плюс добавить'],
  ['heavy_minus_sign', '➖', 'минус'],
  ['heavy_division_sign', '➗', 'разделить'],
  ['curly_loop', '➰', 'петля'],
  ['loop', '➿', 'двойная петля'],
  ['question', '❓', 'вопрос'],
  ['grey_question', '❔', 'вопрос серый'],
  ['grey_exclamation', '❕', 'восклицательный знак серый'],
  ['exclamation', '❗', 'восклицательный знак внимание важно', ['heavy_exclamation_mark']],
  ['bangbang', '‼️', 'двойной восклицательный знак'],
  ['interrobang', '⁉️', 'вопрос восклицание'],
  ['warning', '⚠️', 'внимание предупреждение осторожно'],
  ['no_entry', '⛔', 'въезд запрещён стоп'],
  ['no_entry_sign', '🚫', 'запрещено нельзя'],
  ['stop_sign', '🛑', 'стоп знак', ['octagonal_sign']],
  ['underage', '🔞', '18+'],
  ['arrow_up', '⬆️', 'стрелка вверх'],
  ['arrow_down', '⬇️', 'стрелка вниз'],
  ['arrow_left', '⬅️', 'стрелка влево'],
  ['arrow_right', '➡️', 'стрелка вправо'],
  ['arrow_upper_right', '↗️', 'стрелка вверх вправо'],
  ['arrow_lower_right', '↘️', 'стрелка вниз вправо'],
  ['arrow_lower_left', '↙️', 'стрелка вниз влево'],
  ['arrow_upper_left', '↖️', 'стрелка вверх влево'],
  ['arrow_up_down', '↕️', 'стрелка вверх вниз'],
  ['left_right_arrow', '↔️', 'стрелка влево вправо'],
  ['arrow_right_hook', '↪️', 'стрелка поворот'],
  ['leftwards_arrow_with_hook', '↩️', 'стрелка назад возврат'],
  ['arrows_clockwise', '🔃', 'обновить по часовой'],
  ['arrows_counterclockwise', '🔄', 'обновить повторить refresh'],
  ['repeat', '🔁', 'повтор'],
  ['repeat_one', '🔂', 'повтор один'],
  ['twisted_rightwards_arrows', '🔀', 'перемешать'],
  ['back', '🔙', 'назад'],
  ['end', '🔚', 'конец'],
  ['on', '🔛', 'включено'],
  ['soon', '🔜', 'скоро'],
  ['top', '🔝', 'топ вверх'],
  ['fast_forward', '⏩', 'вперёд перемотка'],
  ['rewind', '⏪', 'назад перемотка'],
  ['arrow_forward', '▶️', 'играть старт play'],
  ['arrow_backward', '◀️', 'назад'],
  ['pause_button', '⏸', 'пауза', ['double_vertical_bar']],
  ['stop_button', '⏹', 'стоп'],
  ['record_button', '⏺', 'запись'],
  ['eject', '⏏', 'извлечь', ['eject_symbol']],
  ['information_source', 'ℹ️', 'информация инфо info'],
  ['new', '🆕', 'новый new'],
  ['free', '🆓', 'бесплатно free'],
  ['up', '🆙', 'вверх up обновление'],
  ['cool', '🆒', 'круто cool'],
  ['ok', '🆗', 'ок ok'],
  ['sos', '🆘', 'помощь sos'],
  ['vs', '🆚', 'против versus'],
  ['id', '🆔', 'идентификатор id'],
  ['ng', '🆖', 'нет ng'],
  ['atm', '🏧', 'банкомат'],
  ['parking', '🅿️', 'парковка'],
  ['copyright', '©️', 'авторские права'],
  ['registered', '®️', 'зарегистрировано'],
  ['tm', '™️', 'торговая марка'],
  ['hash', '#️⃣', 'решётка'],
  ['zero', '0️⃣', 'ноль 0'],
  ['one', '1️⃣', 'один 1'],
  ['two', '2️⃣', 'два 2'],
  ['three', '3️⃣', 'три 3'],
  ['four', '4️⃣', 'четыре 4'],
  ['five', '5️⃣', 'пять 5'],
  ['six', '6️⃣', 'шесть 6'],
  ['seven', '7️⃣', 'семь 7'],
  ['eight', '8️⃣', 'восемь 8'],
  ['nine', '9️⃣', 'девять 9'],
  ['keycap_ten', '🔟', 'десять 10'],
  ['star', '⭐', 'звезда избранное favorite'],
  ['white_circle', '⚪', 'белый круг'],
  ['black_circle', '⚫', 'чёрный круг'],
  ['red_circle', '🔴', 'красный круг'],
  ['large_blue_circle', '🔵', 'синий круг', ['blue_circle']],
  ['large_orange_diamond', '🔶', 'оранжевый ромб'],
  ['large_blue_diamond', '🔷', 'синий ромб'],
  ['small_orange_diamond', '🔸', 'оранжевый ромб малый'],
  ['small_blue_diamond', '🔹', 'синий ромб малый'],
  ['small_red_triangle', '🔺', 'красный треугольник'],
  ['small_red_triangle_down', '🔻', 'красный треугольник вниз'],
  ['diamond_shape_with_a_dot_inside', '💠', 'ромб'],
  ['radio_button', '🔘', 'радиокнопка'],
  ['white_square_button', '🔳', 'белый квадрат'],
  ['black_square_button', '🔲', 'чёрный квадрат'],
  ['black_large_square', '⬛', 'чёрный квадрат'],
  ['white_large_square', '⬜', 'белый квадрат'],
  ['recycle', '♻️', 'переработка'],
  ['trident', '🔱', 'трезубец'],
  ['name_badge', '📛', 'бейдж имя'],
  ['beginner', '🔰', 'новичок'],
  ['o', '⭕', 'круг красный'],
  ['wavy_dash', '〰️', 'волнистая линия'],
  ['sparkle', '❇️', 'искра'],
  ['eight_spoked_asterisk', '✳️', 'звёздочка'],
  ['eight_pointed_black_star', '✴️', 'звезда'],
  ['congratulations', '㊗️', 'поздравление'],
  ['secret', '㊙️', 'секрет'],
  ['mute', '🔇', 'без звука'],
  ['speaker', '🔈', 'динамик'],
  ['sound', '🔉', 'звук тише'],
  ['loud_sound', '🔊', 'звук громко'],
  ['cinema', '🎦', 'кинотеатр'],
  ['signal_strength', '📶', 'сигнал связь'],
  ['vibration_mode', '📳', 'вибрация'],
  ['mobile_phone_off', '📴', 'телефон выключен'],
  ['globe_with_meridians', '🌐', 'интернет глобус сеть web'],
  ['flag_ru', '🇷🇺', 'флаг россия russia', ['ru']],
  ['flag_us', '🇺🇸', 'флаг сша usa', ['us']],
  ['flag_gb', '🇬🇧', 'флаг великобритания uk', ['gb']],
  ['flag_de', '🇩🇪', 'флаг германия', ['de']],
  ['flag_fr', '🇫🇷', 'флаг франция', ['fr']],
  ['flag_ua', '🇺🇦', 'флаг украина', ['ua']],
  ['flag_by', '🇧🇾', 'флаг беларусь', ['by']],
  ['flag_kz', '🇰🇿', 'флаг казахстан', ['kz']],
  ['flag_es', '🇪🇸', 'флаг испания', ['es']],
  ['flag_it', '🇮🇹', 'флаг италия', ['it']],
  ['flag_cn', '🇨🇳', 'флаг китай', ['cn']],
  ['flag_jp', '🇯🇵', 'флаг япония', ['jp']],
]

function build(rows: Row[], category: EmojiCategoryId): StandardEmoji[] {
  return rows.map(([name, char, keywords, aliases]) => ({
    name,
    char,
    keywords: keywords.toLowerCase(),
    ...(aliases ? { aliases } : {}),
    category,
  }))
}

export const STANDARD_EMOJIS: StandardEmoji[] = [
  ...build(SMILEYS, 'smileys'),
  ...build(PEOPLE, 'people'),
  ...build(NATURE, 'nature'),
  ...build(FOOD, 'food'),
  ...build(ACTIVITIES, 'activities'),
  ...build(TRAVEL, 'travel'),
  ...build(OBJECTS, 'objects'),
  ...build(SYMBOLS, 'symbols'),
]

export function emojisOfCategory(id: EmojiCategoryId): StandardEmoji[] {
  return STANDARD_EMOJIS.filter((e) => e.category === id)
}

/** shortcode (основное имя или алиас) → эмодзи */
const SHORTCODE_MAP: Map<string, StandardEmoji> = (() => {
  const map = new Map<string, StandardEmoji>()
  for (const e of STANDARD_EMOJIS) if (!map.has(e.name)) map.set(e.name, e)
  for (const e of STANDARD_EMOJIS) {
    for (const a of e.aliases ?? []) if (!map.has(a)) map.set(a, e)
  }
  return map
})()

/** Найти стандартный эмодзи по shortcode (с двоеточиями или без). */
export function emojiByShortcode(shortcode: string): StandardEmoji | undefined {
  const key = shortcode.trim().replace(/^:+|:+$/g, '').toLowerCase()
  return SHORTCODE_MAP.get(key)
}

const SHORTCODE_RE = /:([a-zA-Z0-9_+-]+):/g

/** Заменить известные стандартные :shortcode: на unicode; неизвестные (кастомные) остаются как есть. */
export function replaceShortcodes(text: string): string {
  return text.replace(SHORTCODE_RE, (match, name: string) => {
    const e = SHORTCODE_MAP.get(name.toLowerCase())
    return e ? e.char : match
  })
}

/** Минимальный вид кастомного эмодзи, нужный для поиска/отрисовки. */
export interface CustomEmojiLike {
  name: string
  aliases?: string[]
  extension?: string
  _id?: string
  _updatedAt?: string
}

function norm(s: string): string {
  return s.toLowerCase().replace(/ё/g, 'е').replace(/^:+|:+$/g, '').trim()
}

/** Подходит ли набор строк под запрос (все слова запроса должны встретиться как подстрока). */
function matches(haystack: string, tokens: string[]): boolean {
  return tokens.every((t) => haystack.includes(t))
}

export function searchStandardEmojis(query: string, limit = 200): StandardEmoji[] {
  const q = norm(query)
  if (!q) return []
  const tokens = q.split(/\s+/).filter(Boolean)
  const scored: Array<{ e: StandardEmoji; score: number }> = []
  for (const e of STANDARD_EMOJIS) {
    const names = [e.name, ...(e.aliases ?? [])].map((n) => n.toLowerCase())
    const hay = `${names.join(' ')} ${norm(e.keywords)}`
    if (!matches(hay, tokens)) continue
    let score = 3
    if (names.some((n) => n === q)) score = 0
    else if (names.some((n) => n.startsWith(q))) score = 1
    else if (names.some((n) => n.includes(q))) score = 2
    scored.push({ e, score })
  }
  scored.sort((a, b) => a.score - b.score)
  return scored.slice(0, limit).map((s) => s.e)
}

export function searchCustomEmojis<T extends CustomEmojiLike>(
  list: T[],
  query: string,
  limit = 200
): T[] {
  const q = norm(query)
  if (!q) return []
  const tokens = q.split(/\s+/).filter(Boolean)
  const scored: Array<{ e: T; score: number }> = []
  for (const e of list) {
    const names = [e.name, ...(e.aliases ?? [])].map((n) => n.toLowerCase())
    if (!matches(names.join(' '), tokens)) continue
    let score = 2
    if (names.some((n) => n === q)) score = 0
    else if (names.some((n) => n.startsWith(q))) score = 1
    scored.push({ e, score })
  }
  scored.sort((a, b) => a.score - b.score)
  return scored.slice(0, limit).map((s) => s.e)
}

/** URL картинки кастомного эмодзи через наш прокси (обходит CORS и авторизацию RC). */
export function customEmojiImageUrl(
  workspaceId: string,
  emoji: { name: string; extension?: string; _id?: string; _updatedAt?: string }
): string {
  const params = new URLSearchParams()
  params.set('name', emoji.name)
  params.set('ext', emoji.extension || 'png')
  if (emoji._id) params.set('id', emoji._id)
  if (emoji._updatedAt) {
    const t = new Date(emoji._updatedAt).getTime()
    if (Number.isFinite(t)) params.set('t', String(t))
  }
  params.set('v', '3')
  return `/api/workspace/${encodeURIComponent(workspaceId)}/emoji-image?${params.toString()}`
}
